/**
 * PetMaster - Catálogo Biológico das 35 Espécies
 * Dividido em 5 Classes com taxas de metabolismo, biomas e curiosidades reais.
 */

export const ANIMAL_CLASSES = {
  MAMMALS: 'Mamíferos',
  BIRDS: 'Aves',
  REPTILES: 'Répteis',
  AMPHIBIANS: 'Anfíbios',
  AQUATIC: 'Aquáticos'
};

export const BIOMES = [
  { id: 'all', name: 'Todos os Biomas', icon: '🌍' },
  { id: 'rainforest', name: 'Floresta Tropical / Amazônia', icon: '🌴' },
  { id: 'wetlands', name: 'Pantanal & Várzeas', icon: '🌾' },
  { id: 'savanna', name: 'Cerrado & Savanas', icon: '☀️' },
  { id: 'ocean', name: 'Oceano & Recifes', icon: '🌊' },
  { id: 'coastal', name: 'Litoral & Manguezais', icon: '🦀' }
];

export const FOOD_ITEMS = [
  { id: 'berry', name: 'Frutas Silvestres', type: 'fruit', cost: 10, hungerVal: 20, happyVal: 5, icon: '🫐', desc: 'Bagas frescas colhidas na mata.' },
  { id: 'leaf', name: 'Folhas Frescas', type: 'leaf', cost: 8, hungerVal: 18, happyVal: 4, icon: '🌿', desc: 'Folhas ricas em fibras para herbívoros.' },
  { id: 'insect', name: 'Insetos Nutritivos', type: 'insect', cost: 15, hungerVal: 25, happyVal: 8, icon: '🦗', desc: 'Ricos em proteína natural.' },
  { id: 'fish', name: 'Peixe Fresco', type: 'meat', cost: 25, hungerVal: 35, happyVal: 10, icon: '🐟', desc: 'Peixe fresco para carnívoros e aquáticos.' },
  { id: 'meat', name: 'Carne Magra', type: 'meat', cost: 35, hungerVal: 45, happyVal: 12, icon: '🥩', desc: 'Fonte nobre de energia para predadores.' },
  { id: 'algae', name: 'Algas Marinhas', type: 'algae', cost: 12, hungerVal: 22, happyVal: 6, icon: '🌱', desc: 'Nutrientes ricos do fundo dos mares.' },
  { id: 'golden_fruit', name: 'Fruta Dourada Rara', type: 'special', cost: 80, hungerVal: 60, happyVal: 30, xpBonus: 50, icon: '✨', desc: 'Fruta mística que revitaliza e concede bônus de XP.' }
];

export const CARE_ITEMS = [
  { id: 'soap', name: 'Sabão Ecológico', cost: 15, hygieneVal: 35, icon: '🧼', desc: 'Biodegradável, limpa sem agredir a pele.' },
  { id: 'sponge', name: 'Esponja de Luffa', cost: 25, hygieneVal: 50, icon: '🧽', desc: 'Esfoliação natural e banho completo.' },
  { id: 'health_potion', name: 'Elixir de Ervas', cost: 50, healthVal: 100, icon: '🧪', desc: 'Cura qualquer doença ou mal-estar do pet.' },
  { id: 'energy_tonic', name: 'Tônico Revigorante', cost: 40, energyVal: 50, icon: '⚡', desc: 'Restaura a energia sem precisar dormir.' }
];

export const SPECIES_DATABASE = [
  // ==========================================
  // 1. MAMÍFEROS (7)
  // ==========================================
  {
    id: 'capybara',
    name: 'Capivara',
    scientificName: 'Hydrochoerus hydrochaeris',
    class: ANIMAL_CLASSES.MAMMALS,
    biome: 'wetlands',
    biomeName: 'Pantanal & Várzeas',
    dietType: 'herbivore',
    favoriteFood: 'Folhas Frescas',
    emoji: '🐾',
    icon: '🐾',
    eggColor: '#d97706',
    rarity: 'comum',
    decayRates: { hunger: 1.1, hygiene: 0.9, energy: 1.0, happiness: 0.8 },
    curiosity: 'É o maior roedor do mundo e possui uma sociabilidade lendária, convivendo em harmonia com diversas espécies.',
    stageIcons: { egg: '🥚', baby: '🐹', teen: '🦫', adult: '🐾' }
  },
  {
    id: 'jaguar',
    name: 'Onça-Pintada',
    scientificName: 'Panthera onca',
    class: ANIMAL_CLASSES.MAMMALS,
    biome: 'rainforest',
    biomeName: 'Floresta Tropical',
    dietType: 'carnivore',
    favoriteFood: 'Carne Magra',
    emoji: '🐆',
    icon: '🐆',
    eggColor: '#f59e0b',
    rarity: 'lendário',
    decayRates: { hunger: 1.3, hygiene: 1.0, energy: 1.2, happiness: 1.1 },
    curiosity: 'Possui a mordida mais poderosa entre todos os felinos em relação ao tamanho corporal, capaz de perfurar cascos de tartaruga.',
    stageIcons: { egg: '🥚', baby: '🐱', teen: '🐆', adult: '🐅' }
  },
  {
    id: 'maned_wolf',
    name: 'Lobo-Guará',
    scientificName: 'Chrysocyon brachyurus',
    class: ANIMAL_CLASSES.MAMMALS,
    biome: 'savanna',
    biomeName: 'Cerrado',
    dietType: 'omnivore',
    favoriteFood: 'Frutas Silvestres',
    emoji: '🐺',
    icon: '🐺',
    eggColor: '#ea580c',
    rarity: 'raro',
    decayRates: { hunger: 1.0, hygiene: 1.0, energy: 1.1, happiness: 1.0 },
    curiosity: 'Símbolo do Cerrado brasileiro, suas pernas longas são uma adaptação evolutiva para enxergar sobre a vegetação alta.',
    stageIcons: { egg: '🥚', baby: '🦊', teen: '🐺', adult: '🐕' }
  },
  {
    id: 'golden_lion_tamarin',
    name: 'Mico-Leão-Dourado',
    scientificName: 'Leontopithecus rosalia',
    class: ANIMAL_CLASSES.MAMMALS,
    biome: 'rainforest',
    biomeName: 'Floresta Tropical',
    dietType: 'omnivore',
    favoriteFood: 'Frutas Silvestres',
    emoji: '🐒',
    icon: '🐒',
    eggColor: '#f59e0b',
    rarity: 'raro',
    decayRates: { hunger: 1.2, hygiene: 1.2, energy: 1.3, happiness: 1.2 },
    curiosity: 'Símbolo mundial de conservação da Mata Atlântica; quase foi extinto e recuperou sua população graças a santuários.',
    stageIcons: { egg: '🥚', baby: '🐵', teen: '🐒', adult: '🦁' }
  },
  {
    id: 'sloth',
    name: 'Bicho-Preguiça',
    scientificName: 'Bradypus tridactylus',
    class: ANIMAL_CLASSES.MAMMALS,
    biome: 'rainforest',
    biomeName: 'Floresta Tropical',
    dietType: 'herbivore',
    favoriteFood: 'Folhas Frescas',
    emoji: '🦥',
    icon: '🦥',
    eggColor: '#78716c',
    rarity: 'incomum',
    decayRates: { hunger: 0.6, hygiene: 0.7, energy: 0.5, happiness: 0.7 },
    curiosity: 'Possui um dos metabolismos mais lentos do reino animal, digerindo uma única folha por semanas.',
    stageIcons: { egg: '🥚', baby: '🐨', teen: '🦥', adult: '🦥' }
  },
  {
    id: 'giant_anteater',
    name: 'Tamanduá-Bandeira',
    scientificName: 'Myrmecophaga tridactyla',
    class: ANIMAL_CLASSES.MAMMALS,
    biome: 'savanna',
    biomeName: 'Cerrado',
    dietType: 'insectivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🦡',
    icon: '🦡',
    eggColor: '#71717a',
    rarity: 'incomum',
    decayRates: { hunger: 1.1, hygiene: 1.0, energy: 1.0, happiness: 0.9 },
    curiosity: 'Não possui dentes e usa sua língua comprida de até 60 cm para consumir até 30 mil formigas e cupins por dia.',
    stageIcons: { egg: '🥚', baby: '🐭', teen: '🦡', adult: '🐾' }
  },
  {
    id: 'tapir',
    name: 'Anta',
    scientificName: 'Tapirus terrestris',
    class: ANIMAL_CLASSES.MAMMALS,
    biome: 'rainforest',
    biomeName: 'Floresta Tropical',
    dietType: 'herbivore',
    favoriteFood: 'Folhas Frescas',
    emoji: '🦛',
    icon: '🦛',
    eggColor: '#52525b',
    rarity: 'comum',
    decayRates: { hunger: 1.2, hygiene: 1.1, energy: 0.9, happiness: 0.9 },
    curiosity: 'Conhecida como a "jardineira das florestas", pois dispersa sementes por quilômetros através de suas fezes.',
    stageIcons: { egg: '🥚', baby: '🐗', teen: '🦛', adult: '🦣' }
  },

  // ==========================================
  // 2. AVES (7)
  // ==========================================
  {
    id: 'hyacinth_macaw',
    name: 'Arara-Azul',
    scientificName: 'Anodorhynchus hyacinthinus',
    class: ANIMAL_CLASSES.BIRDS,
    biome: 'wetlands',
    biomeName: 'Pantanal',
    dietType: 'herbivore',
    favoriteFood: 'Frutas Silvestres',
    emoji: '🦜',
    icon: '🦜',
    eggColor: '#2563eb',
    rarity: 'lendário',
    decayRates: { hunger: 1.1, hygiene: 1.3, energy: 1.2, happiness: 1.1 },
    curiosity: 'É a maior espécie de arara do mundo; formam casais monogâmicos que permanecem juntos por toda a vida.',
    stageIcons: { egg: '🥚', baby: '🐣', teen: '🐥', adult: '🦜' }
  },
  {
    id: 'toco_toucan',
    name: 'Tucano-Toco',
    scientificName: 'Ramphastos toco',
    class: ANIMAL_CLASSES.BIRDS,
    biome: 'savanna',
    biomeName: 'Cerrado & Florestas',
    dietType: 'omnivore',
    favoriteFood: 'Frutas Silvestres',
    emoji: '🦤',
    icon: '🦤',
    eggColor: '#f97316',
    rarity: 'comum',
    decayRates: { hunger: 1.2, hygiene: 1.2, energy: 1.1, happiness: 1.0 },
    curiosity: 'Seu enorme bico não serve apenas para colher frutas, mas também funciona como um radiador térmico corporal.',
    stageIcons: { egg: '🥚', baby: '🐣', teen: '🐦', adult: '🦤' }
  },
  {
    id: 'hummingbird',
    name: 'Beija-Flor',
    scientificName: 'Trochilidae',
    class: ANIMAL_CLASSES.BIRDS,
    biome: 'rainforest',
    biomeName: 'Mata Atlântica',
    dietType: 'herbivore',
    favoriteFood: 'Fruta Dourada Rara',
    emoji: '🕊️',
    icon: '🕊️',
    eggColor: '#06b6d4',
    rarity: 'incomum',
    decayRates: { hunger: 1.6, hygiene: 1.1, energy: 1.5, happiness: 1.2 },
    curiosity: 'É a única ave capaz de voar para trás e para os lados, batendo as asas até 80 vezes por segundo.',
    stageIcons: { egg: '🥚', baby: '🐣', teen: '🐤', adult: '🕊️' }
  },
  {
    id: 'magellanic_penguin',
    name: 'Pinguim-de-Magalhães',
    scientificName: 'Spheniscus magellanicus',
    class: ANIMAL_CLASSES.BIRDS,
    biome: 'coastal',
    biomeName: 'Litoral Sul',
    dietType: 'carnivore',
    favoriteFood: 'Peixe Fresco',
    emoji: '🐧',
    icon: '🐧',
    eggColor: '#0f172a',
    rarity: 'incomum',
    decayRates: { hunger: 1.2, hygiene: 1.0, energy: 1.1, happiness: 1.0 },
    curiosity: 'Excelente nadador marinho, migra milhares de quilômetros todo inverno da Patagônia até a costa brasileira.',
    stageIcons: { egg: '🥚', baby: '🐣', teen: '🐧', adult: '🐧' }
  },
  {
    id: 'burrowing_owl',
    name: 'Coruja-Buraqueira',
    scientificName: 'Athene cunicularia',
    class: ANIMAL_CLASSES.BIRDS,
    biome: 'savanna',
    biomeName: 'Campos & Cerrado',
    dietType: 'carnivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🦉',
    icon: '🦉',
    eggColor: '#a16207',
    rarity: 'comum',
    decayRates: { hunger: 1.0, hygiene: 1.1, energy: 0.9, happiness: 0.9 },
    curiosity: 'Ao contrário da maioria das corujas, tem hábitos diurnos e constrói seus ninhos em buracos no chão.',
    stageIcons: { egg: '🥚', baby: '🐣', teen: '🐥', adult: '🦉' }
  },
  {
    id: 'harpy_eagle',
    name: 'Harpia (Gavião-Real)',
    scientificName: 'Harpia harpyja',
    class: ANIMAL_CLASSES.BIRDS,
    biome: 'rainforest',
    biomeName: 'Amazônia',
    dietType: 'carnivore',
    favoriteFood: 'Carne Magra',
    emoji: '🦅',
    icon: '🦅',
    eggColor: '#475569',
    rarity: 'lendário',
    decayRates: { hunger: 1.3, hygiene: 1.0, energy: 1.2, happiness: 1.1 },
    curiosity: 'A ave de rapina mais poderosa do planeta; suas garras são maiores que as de um urso pardo.',
    stageIcons: { egg: '🥚', baby: '🐣', teen: '🦅', adult: '🦅' }
  },
  {
    id: 'flamingo',
    name: 'Flamingo',
    scientificName: 'Phoenicopterus roseus',
    class: ANIMAL_CLASSES.BIRDS,
    biome: 'coastal',
    biomeName: 'Litoral & Lagoas',
    dietType: 'omnivore',
    favoriteFood: 'Algas Marinhas',
    emoji: '🦩',
    icon: '🦩',
    eggColor: '#f43f5e',
    rarity: 'raro',
    decayRates: { hunger: 1.1, hygiene: 1.4, energy: 1.0, happiness: 1.1 },
    curiosity: 'Sua cor rosa marcante vem dos pigmentos carotenoides presentes nas algas e pequenos crustáceos que consome.',
    stageIcons: { egg: '🥚', baby: '🐣', teen: '🦩', adult: '🦩' }
  },

  // ==========================================
  // 3. RÉPTEIS (7)
  // ==========================================
  {
    id: 'caiman',
    name: 'Jacaré-do-Pantanal',
    scientificName: 'Caiman yacare',
    class: ANIMAL_CLASSES.REPTILES,
    biome: 'wetlands',
    biomeName: 'Pantanal',
    dietType: 'carnivore',
    favoriteFood: 'Peixe Fresco',
    emoji: '🐊',
    icon: '🐊',
    eggColor: '#15803d',
    rarity: 'comum',
    decayRates: { hunger: 0.8, hygiene: 0.9, energy: 0.8, happiness: 0.9 },
    curiosity: 'Tem papel ecológico fundamental no controle da população de piranhas e renovação dos cursos d’água.',
    stageIcons: { egg: '🥚', baby: '🦎', teen: '🐊', adult: '🐊' }
  },
  {
    id: 'green_turtle',
    name: 'Tartaruga-Verde',
    scientificName: 'Chelonia mydas',
    class: ANIMAL_CLASSES.REPTILES,
    biome: 'ocean',
    biomeName: 'Oceano & Recifes',
    dietType: 'herbivore',
    favoriteFood: 'Algas Marinhas',
    emoji: '🐢',
    icon: '🐢',
    eggColor: '#059669',
    rarity: 'raro',
    decayRates: { hunger: 0.7, hygiene: 0.8, energy: 0.7, happiness: 0.8 },
    curiosity: 'Navega milhares de quilômetros usando o campo magnético da Terra para desovar exatamente na praia onde nasceu.',
    stageIcons: { egg: '🥚', baby: '🐢', teen: '🐢', adult: '🐢' }
  },
  {
    id: 'chameleon',
    name: 'Camaleão',
    scientificName: 'Chamaeleo calyptratus',
    class: ANIMAL_CLASSES.REPTILES,
    biome: 'rainforest',
    biomeName: 'Florestas',
    dietType: 'insectivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🦎',
    icon: '🦎',
    eggColor: '#10b981',
    rarity: 'incomum',
    decayRates: { hunger: 0.9, hygiene: 0.9, energy: 0.8, happiness: 1.0 },
    curiosity: 'Seus olhos se movem de forma totalmente independente em 360°, e sua pele muda de cor por comunicação e temperatura.',
    stageIcons: { egg: '🥚', baby: '🦎', teen: '🦎', adult: '🦎' }
  },
  {
    id: 'anaconda',
    name: 'Sucuri-Verde',
    scientificName: 'Eunectes murinus',
    class: ANIMAL_CLASSES.REPTILES,
    biome: 'wetlands',
    biomeName: 'Pantanal & Rios',
    dietType: 'carnivore',
    favoriteFood: 'Carne Magra',
    emoji: '🐍',
    icon: '🐍',
    eggColor: '#166534',
    rarity: 'raro',
    decayRates: { hunger: 0.6, hygiene: 0.9, energy: 0.7, happiness: 0.9 },
    curiosity: 'A cobra mais pesada do mundo; excelente nadadora que passa a maior parte da vida submersa em rios.',
    stageIcons: { egg: '🥚', baby: '🐍', teen: '🐍', adult: '🐉' }
  },
  {
    id: 'tegu_lizard',
    name: 'Teiú',
    scientificName: 'Salvator merianae',
    class: ANIMAL_CLASSES.REPTILES,
    biome: 'savanna',
    biomeName: 'Cerrado & Caatinga',
    dietType: 'omnivore',
    favoriteFood: 'Frutas Silvestres',
    emoji: '🦎',
    icon: '🦎',
    eggColor: '#65a30d',
    rarity: 'comum',
    decayRates: { hunger: 0.9, hygiene: 0.9, energy: 0.9, happiness: 0.9 },
    curiosity: 'Um dos maiores lagartos sul-americanos; possui inteligência notável e reconhece cuidadores pelo odor.',
    stageIcons: { egg: '🥚', baby: '🦎', teen: '🦎', adult: '🦖' }
  },
  {
    id: 'bearded_dragon',
    name: 'Dragão-Barbudo',
    scientificName: 'Pogona vitticeps',
    class: ANIMAL_CLASSES.REPTILES,
    biome: 'savanna',
    biomeName: 'Regiões Áridas',
    dietType: 'omnivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🐲',
    icon: '🐲',
    eggColor: '#d97706',
    rarity: 'incomum',
    decayRates: { hunger: 0.8, hygiene: 0.9, energy: 0.8, happiness: 0.9 },
    curiosity: 'Quando ameaçado ou cortejando, infla sua garganta cheia de escamas espinhosas que escurecem como uma barba.',
    stageIcons: { egg: '🥚', baby: '🦎', teen: '🐲', adult: '🐉' }
  },
  {
    id: 'iguana',
    name: 'Iguana-Verde',
    scientificName: 'Iguana iguana',
    class: ANIMAL_CLASSES.REPTILES,
    biome: 'rainforest',
    biomeName: 'Copas das Árvores',
    dietType: 'herbivore',
    favoriteFood: 'Folhas Frescas',
    emoji: '🦎',
    icon: '🦎',
    eggColor: '#84cc16',
    rarity: 'comum',
    decayRates: { hunger: 0.8, hygiene: 0.9, energy: 0.9, happiness: 0.9 },
    curiosity: 'Possui um "terceiro olho" no topo do crânio chamado olho parietal, que detecta variações de luz e sombras de predadores aéreos.',
    stageIcons: { egg: '🥚', baby: '🦎', teen: '🦎', adult: '🦎' }
  },

  // ==========================================
  // 4. ANFÍBIOS (7)
  // ==========================================
  {
    id: 'axolotl',
    name: 'Axolote',
    scientificName: 'Ambystoma mexicanum',
    class: ANIMAL_CLASSES.AMPHIBIANS,
    biome: 'wetlands',
    biomeName: 'Lagos & Águas Doces',
    dietType: 'carnivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🫧',
    icon: '🫧',
    eggColor: '#ec4899',
    rarity: 'lendário',
    decayRates: { hunger: 1.0, hygiene: 1.5, energy: 0.9, happiness: 1.1 },
    curiosity: 'Mantém suas brânquias externas por toda a vida e tem a incrível capacidade de regenerar membros e órgãos vitais inteiros.',
    stageIcons: { egg: '🥚', baby: '🫧', teen: '🐠', adult: '🫧' }
  },
  {
    id: 'cane_toad',
    name: 'Sapo-Cururu',
    scientificName: 'Rhinella marina',
    class: ANIMAL_CLASSES.AMPHIBIANS,
    biome: 'wetlands',
    biomeName: 'Zonas Úmidas',
    dietType: 'insectivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🐸',
    icon: '🐸',
    eggColor: '#4d7c0f',
    rarity: 'comum',
    decayRates: { hunger: 0.9, hygiene: 1.4, energy: 0.8, happiness: 0.8 },
    curiosity: 'Famoso pelo seu canto grave no período reprodutivo, é um voraz predador de pragas e insetos noturnos.',
    stageIcons: { egg: '🥚', baby: '🐟', teen: '🐸', adult: '🐸' }
  },
  {
    id: 'golden_poison_frog',
    name: 'Rã-Dardo-Dourada',
    scientificName: 'Phyllobates terribilis',
    class: ANIMAL_CLASSES.AMPHIBIANS,
    biome: 'rainforest',
    biomeName: 'Selva Úmida',
    dietType: 'insectivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🐸',
    icon: '🐸',
    eggColor: '#eab308',
    rarity: 'raro',
    decayRates: { hunger: 1.1, hygiene: 1.5, energy: 1.1, happiness: 1.0 },
    curiosity: 'Um dos animais mais venenosos do planeta; sua coloração dourada chamativa é um aviso biológico (aposematismo).',
    stageIcons: { egg: '🥚', baby: '🐟', teen: '🐸', adult: '🐸' }
  },
  {
    id: 'fire_salamander',
    name: 'Salamandra-de-Fogo',
    scientificName: 'Salamandra salamandra',
    class: ANIMAL_CLASSES.AMPHIBIANS,
    biome: 'rainforest',
    biomeName: 'Florestas Úmidas',
    dietType: 'insectivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🦎',
    icon: '🦎',
    eggColor: '#f97316',
    rarity: 'incomum',
    decayRates: { hunger: 1.0, hygiene: 1.4, energy: 0.9, happiness: 0.9 },
    curiosity: 'Na mitologia antiga, acreditava-se que nascia do fogo porque costumava se esconder dentro de troncos de lenha.',
    stageIcons: { egg: '🥚', baby: '🐟', teen: '🦎', adult: '🦎' }
  },
  {
    id: 'green_tree_frog',
    name: 'Perereca-Verde',
    scientificName: 'Hyla cinerea',
    class: ANIMAL_CLASSES.AMPHIBIANS,
    biome: 'wetlands',
    biomeName: 'Vegetação Marginal',
    dietType: 'insectivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🐸',
    icon: '🐸',
    eggColor: '#22c55e',
    rarity: 'comum',
    decayRates: { hunger: 1.0, hygiene: 1.5, energy: 1.0, happiness: 1.0 },
    curiosity: 'Possui discos adesivos na ponta dos dedos que funcionam por capilaridade para escalar folhas lisas e vidros.',
    stageIcons: { egg: '🥚', baby: '🐟', teen: '🐸', adult: '🐸' }
  },
  {
    id: 'crested_newt',
    name: 'Tríton-Crestado',
    scientificName: 'Triturus cristatus',
    class: ANIMAL_CLASSES.AMPHIBIANS,
    biome: 'wetlands',
    biomeName: 'Lagos & Charcos',
    dietType: 'carnivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🦎',
    icon: '🦎',
    eggColor: '#0284c7',
    rarity: 'incomum',
    decayRates: { hunger: 0.9, hygiene: 1.4, energy: 0.9, happiness: 0.9 },
    curiosity: 'Os machos desenvolvem uma crista dorsal ondulada impressionante parecida com a de um dragão durante a época reprodutiva.',
    stageIcons: { egg: '🥚', baby: '🐟', teen: '🦎', adult: '🦎' }
  },
  {
    id: 'ringed_caecilian',
    name: 'Cecília-Azul (Cobra-Cega)',
    scientificName: 'Siphonops annulatus',
    class: ANIMAL_CLASSES.AMPHIBIANS,
    biome: 'rainforest',
    biomeName: 'Subsolo de Florestas',
    dietType: 'carnivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🪱',
    icon: '🪱',
    eggColor: '#3b82f6',
    rarity: 'raro',
    decayRates: { hunger: 0.8, hygiene: 1.6, energy: 0.8, happiness: 0.8 },
    curiosity: 'Anfíbio ápode (sem patas) que vive debaixo da terra; as mães alimentam seus filhotes com a camada externa da própria pele.',
    stageIcons: { egg: '🥚', baby: '🪱', teen: '🪱', adult: '🐍' }
  },

  // ==========================================
  // 5. AQUÁTICOS (7)
  // ==========================================
  {
    id: 'clownfish',
    name: 'Peixe-Palhaço',
    scientificName: 'Amphiprion ocellaris',
    class: ANIMAL_CLASSES.AQUATIC,
    biome: 'ocean',
    biomeName: 'Recifes de Coral',
    dietType: 'omnivore',
    favoriteFood: 'Algas Marinhas',
    emoji: '🐠',
    icon: '🐠',
    eggColor: '#ea580c',
    rarity: 'comum',
    decayRates: { hunger: 1.1, hygiene: 1.2, energy: 1.0, happiness: 1.0 },
    curiosity: 'Possui uma camada de muco que o protege das picadas venenosas das anêmonas, vivendo em simbiose mútua perfeita.',
    stageIcons: { egg: '🥚', baby: '🐟', teen: '🐠', adult: '🐠' }
  },
  {
    id: 'manatee',
    name: 'Peixe-Boi da Amazônia',
    scientificName: 'Trichechus inunguis',
    class: ANIMAL_CLASSES.AQUATIC,
    biome: 'wetlands',
    biomeName: 'Rios Amazônicos',
    dietType: 'herbivore',
    favoriteFood: 'Folhas Frescas',
    emoji: '🦭',
    icon: '🦭',
    eggColor: '#64748b',
    rarity: 'raro',
    decayRates: { hunger: 1.2, hygiene: 1.1, energy: 0.8, happiness: 0.9 },
    curiosity: 'Exclusivamente de água doce, pode ingerir mais de 10% do seu peso corporal em plantas aquáticas todos os dias.',
    stageIcons: { egg: '🥚', baby: '🐟', teen: '🦭', adult: '🐋' }
  },
  {
    id: 'whale_shark',
    name: 'Tubarão-Baleia',
    scientificName: 'Rhincodon typus',
    class: ANIMAL_CLASSES.AQUATIC,
    biome: 'ocean',
    biomeName: 'Mar Aberto',
    dietType: 'omnivore',
    favoriteFood: 'Algas Marinhas',
    emoji: '🦈',
    icon: '🦈',
    eggColor: '#1e3a8a',
    rarity: 'lendário',
    decayRates: { hunger: 1.4, hygiene: 1.0, energy: 0.9, happiness: 1.0 },
    curiosity: 'O maior peixe vivo do planeta; apesar de gigante, é completamente dócil e alimenta-se apenas por filtração de plâncton.',
    stageIcons: { egg: '🥚', baby: '🐟', teen: '🦈', adult: '🐋' }
  },
  {
    id: 'octopus',
    name: 'Polvo-Comum',
    scientificName: 'Octopus vulgaris',
    class: ANIMAL_CLASSES.AQUATIC,
    biome: 'ocean',
    biomeName: 'Costões Rochosos',
    dietType: 'carnivore',
    favoriteFood: 'Peixe Fresco',
    emoji: '🐙',
    icon: '🐙',
    eggColor: '#8b5cf6',
    rarity: 'raro',
    decayRates: { hunger: 1.1, hygiene: 1.1, energy: 1.2, happiness: 1.2 },
    curiosity: 'Possui três corações, sangue azul e 9 cérebros (um central e um menor independente em cada tentáculo).',
    stageIcons: { egg: '🥚', baby: '🦑', teen: '🐙', adult: '🐙' }
  },
  {
    id: 'seahorse',
    name: 'Cavalo-Marinho',
    scientificName: 'Hippocampus',
    class: ANIMAL_CLASSES.AQUATIC,
    biome: 'coastal',
    biomeName: 'Manguezais & Recifes',
    dietType: 'carnivore',
    favoriteFood: 'Insetos Nutritivos',
    emoji: '🫧',
    icon: '🫧',
    eggColor: '#eab308',
    rarity: 'incomum',
    decayRates: { hunger: 1.3, hygiene: 1.2, energy: 0.9, happiness: 1.0 },
    curiosity: 'É um dos raríssimos casos no reino animal onde é o macho quem engravida e dá à luz as centenas de filhotes.',
    stageIcons: { egg: '🥚', baby: '🐟', teen: '🐠', adult: '🫧' }
  },
  {
    id: 'spinner_dolphin',
    name: 'Golfinho-Rotador',
    scientificName: 'Stenella longirostris',
    class: ANIMAL_CLASSES.AQUATIC,
    biome: 'ocean',
    biomeName: 'Arquipélagos Oceânicos',
    dietType: 'carnivore',
    favoriteFood: 'Peixe Fresco',
    emoji: '🐬',
    icon: '🐬',
    eggColor: '#38bdf8',
    rarity: 'raro',
    decayRates: { hunger: 1.2, hygiene: 1.1, energy: 1.3, happiness: 1.3 },
    curiosity: 'Famoso por seus saltos acrobáticos girando até 7 vezes no ar antes de retornar suavemente à água.',
    stageIcons: { egg: '🥚', baby: '🐬', teen: '🐬', adult: '🐬' }
  },
  {
    id: 'moon_jellyfish',
    name: 'Água-Viva-Lua',
    scientificName: 'Aurelia aurita',
    class: ANIMAL_CLASSES.AQUATIC,
    biome: 'ocean',
    biomeName: 'Águas Costeiras',
    dietType: 'carnivore',
    favoriteFood: 'Algas Marinhas',
    emoji: '🪼',
    icon: '🪼',
    eggColor: '#c084fc',
    rarity: 'incomum',
    decayRates: { hunger: 0.9, hygiene: 1.3, energy: 0.7, happiness: 0.8 },
    curiosity: 'Composta por mais de 95% de água, flutua pelas correntes marinhas e não tem cérebro, coração nem ossos.',
    stageIcons: { egg: '🥚', baby: '🫧', teen: '🪼', adult: '🪼' }
  }
];

export function getSpeciesById(id) {
  return SPECIES_DATABASE.find(s => s.id === id) || SPECIES_DATABASE[0];
}

export function getSpeciesByClass(className) {
  return SPECIES_DATABASE.filter(s => s.class === className);
}

export function getSpeciesByBiome(biomeId) {
  if (!biomeId || biomeId === 'all') return SPECIES_DATABASE;
  return SPECIES_DATABASE.filter(s => s.biome === biomeId);
}
